### ISSUE TITLE
Does this use API v2? 

### ISSUE THREAD

**Issue by brushj** [thechrisreese/Homebridge-winkv2#1]
Can we use our personal Wink credentials for this instead of the default android one that everyone has been using?

**Comment by thechrisreese** [comment]
Not yet but that's what I'm doing behind the scenes.  This one is still very much a work in progress.  I had cameras and security devices but they're still rough around the edges.

**Comment by thechrisreese** [comment]
However, if you want to use V2 credentials you can edit wink.js to do that. But it will cause server disconnects because V2  doesn't allow polling as often as this thing is built to do.

**Comment by brushj** [comment]
Gotcha, was more of a curiosity than anything else. I want to try this out because it has the Canary support, which is the only other thing that I was really interested in support for. Thanks for working on it this.

**Comment by thechrisreese** [comment]
Canary will GET but I can't figure out SET. So it will show status and notify on status change.

**Comment by thechrisreese** [comment]
I have an Homebridge-IFTTT workaround for setting Canary if you want me to detail in the meantime.

**Comment by brushj** [comment]
That's all I really need, everything else is based off of time of day or location based.

**Comment by thechrisreese** [comment]
Let me know if this doesn't recognize your Canary I believe I have work to do on the device ID
